version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - modernize
    - nakedret
    - revive
    - staticcheck
    - testifylint
    - unused

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

  settings:
    staticcheck:
      checks:
        - "all"
        - -ST1000

run:
  timeout: 5m

